# Generated by Django 4.1.2 on 2022-10-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.TextField(max_length=30)),
                ('alokatze_data', models.TextField(max_length=50)),
                ('kolorea', models.TextField(max_length=20)),
                ('modeloa', models.TextField(max_length=30)),
                ('prezioa', models.IntegerField()),
            ],
        ),
    ]
