# Generated by Django 4.1.2 on 2022-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.TextField(max_length=30)),
                ('abizena', models.TextField(max_length=30)),
                ('herria', models.TextField(max_length=30)),
            ],
        ),
    ]
